spring:
  application:
    name: Cloudstorage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/my_sql_cloud_storage_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: true
  session:
    store-type: redis
    timeout: 30m
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server:
  port: 8080


app:
  storage:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: user-files

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true


